apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flui-backend.fullname" . }}
  labels:
    {{- include "flui-backend.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  DB_HOST: {{ .Values.database.host | quote }}
  DB_PORT: {{ .Values.database.port | quote }}
  DB_NAME: {{ .Values.database.name | quote }}
  DB_USER: {{ .Values.database.user | quote }}
  DB_DIALECT: "postgres"
  SWAGGER_USER: {{ .Values.swagger.user | default "admin" | quote }}
  SWAGGER_PASSWORD: {{ .Values.swagger.password | default "admin123" | quote }}
