{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flui-backend.fullname" . }}-db-secret
  labels:
    {{- include "flui-backend.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.database }}
  DB_HOST: {{ .host | b64enc | quote }}
  DB_PORT: {{ .port | toString | b64enc | quote }}
  DB_NAME: {{ .name | b64enc | quote }}
  DB_USER: {{ .user | b64enc | quote }}
  {{- if .password }}
  DB_PASSWORD: {{ .password | b64enc | quote }}
  {{- end }}
  {{- end }}
stringData:
  {{- if not .Values.database.password }}
  DB_PASSWORD: "CHANGE_ME_IN_PRODUCTION"
  {{- end }}
{{- end }}
