{{- if and .Values.rollout.enabled (eq .Values.rollout.strategy "blueGreen") }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flui-backend.fullname" . }}-active
  labels:
    {{- include "flui-backend.labels" . | nindent 4 }}
    service-type: active
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "flui-backend.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flui-backend.fullname" . }}-preview
  labels:
    {{- include "flui-backend.labels" . | nindent 4 }}
    service-type: preview
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "flui-backend.selectorLabels" . | nindent 4 }}
{{- end }}
