{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flui-backend.serviceAccountName" . }}
  labels:
    {{- include "flui-backend.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
