# Valores espec√≠ficos para ambiente de DESENVOLVIMENTO
replicaCount: 1

image:
  repository: ghcr.io/ianjairo/flui-backend
  tag: "dev-0705fb2"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-secret


env:
  NODE_ENV: development
  PORT: "3000"

swagger:
  user: admin
  password: "SenhaForteDocs@2025!"
  
database:
  host: postgres-postgresql
  port: 5432
  name: flui_dev
  user: postgres
  existingSecret: "flui-db-secret"

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false

ingress:
  enabled: true
  hosts:
    - host: api-dev.flui.local
      paths:
        - path: /
          pathType: Prefix

migration:
  enabled: false
