# Valores espec√≠ficos para ambiente de DESENVOLVIMENTO
replicaCount: 1

image:
  repository: ghcr.io/ianjairo/flui-backend
  tag: "dev-8055404"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-secret


env:
  NODE_ENV: development
  PORT: "3000"

swagger:
  user: admin
  password: "SenhaForteDocs@2025!"
  
database:
  host: postgres-cluster-rw
  port: 5432
  name: flui_dev
  user: flui
  existingSecret: "flui-db-secret"

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

autoscaling:
  enabled: false

ingress:
  enabled: true
  hosts:
    - host: api-dev.flui.local
      paths:
        - path: /
          pathType: Prefix

migration:
  enabled: false

rollout:
  enabled: true
  strategy: blueGreen
  blueGreen:
    autoPromotionEnabled: false
    scaleDownDelaySeconds: 30
    previewReplicaCount: 1

