# Valores específicos para ambiente de PRODUÇÃO
replicaCount: 3

image:
  repository: ghcr.io/ianjairo/flui-backend
  tag: "prod-5706fbe"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-secret

env:
  NODE_ENV: production
  PORT: "3000"

swagger:
  user: admin
  password: "SenhaProdForte@2025!"

database:
  host: postgres-cluster-prod-rw
  port: 5432
  name: flui_prod
  user: flui
  existingSecret: "flui-db-prod-secret"

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 7
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: api.flui.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: flui-prod-tls
      hosts:
        - api.flui.com

migration:
  enabled: true
